name: GitHub Pages

on:
  push:
    branches:
      - $default-branch
      # - main
  workflow_dispatch:
    inputs:
      cache:
        description: 'Cache yarn & .next'
        required: false
        default: true
        type: boolean
      branch:
        description: 'Branch to deploy'
        required: false
        default: $default-branch
        type: string

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: 'pages'
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: ${{ inputs.cache && 'yarn' || ''}}

      - id: configurepages
        uses: actions/configure-pages@v5

    #   - name: Restore cache
    #     uses: actions/cache@v4
    #     if: ${{ inputs.cache }}
    #     with:
    #       path: .next/cache
    #       # Generate a new cache whenever packages or source files change.
    #       key: ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json', '**/yarn.lock') }}-${{ hashFiles('**.[jt]s', '**.[jt]sx') }}
    #       # If source files changed but packages didn't, rebuild from a prior cache.
    #       restore-keys: |
    #         ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json', '**/yarn.lock') }}-

      - name: Install dependencies
        run: npm install
      - name: 🏗️ Build
        run: npm run build

      - uses: actions/upload-pages-artifact@v3
        with:
          path: ./dist

  # Deployment job
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
